version: "3.5"
services:
  # api:
  #   container_name: "echotime_api"
  #   build:
  #     context: "./api"
  #     dockerfile: "Dockerfile"
  #   restart: "always"
  #   ports:
  #     - "4000:4000"
  #   tty: true
  #   networks:
  #     - "echotimeservices"
  redis:
    container_name: "echotime_redis"
    image: "redis:6.0-alpine"
    command: "redis-server --requirepass ${REDISPWD} --appendonly yes"
    restart: "always"
    tty: true
    ports:
      - "6379:6379"
    volumes:
      - "./data:/var/lib/redis"
      - "./redis.conf:/usr/local/etc/redis/redis.conf"
    networks:
      - "echotimeservices"
  redisadmin:
    container_name: "echotime_redisadmin"
    image: "erikdubbelboer/phpredisadmin"
    restart: "always"
    tty: true
    ports:
      - "8080:80"
    environment:
      - "REDIS_1_HOST=echotime_redis"
      - "REDIS_1_PORT=6379"
      - "REDIS_1_NAME=echotime_redis"
      - "REDIS_1_AUTH=${REDISPWD}"
      - "ADMIN_USER=admin"
      - "ADMIN_PASS=admin"
    networks:
      - "echotimeservices"
networks:
  echotimeservices:
    driver: "bridge"
    name: "echotimeservicesbridge"
